# Change these first
owner: hajeekn-co # Your GitHub organization or username
repo: testweb # Your GitHub repository name

# Add your sites here
sites:
  - name: Main Blog
    url: https://blog.slqwq.cn
  - name: HomePage
    url: https://slqwq.cn
  - name: Other CDN
    url: https://moecdn.slqwq.cn
  - name: Static Files CDN
    url: https://static.slqwq.cn
  - name: Static Files CDN Two
    url: https://static-2.slqwq.cn
  - name: Static Files CDN Three
    url: https://static-3.slqwq.cn
  - name: Unpkg Mirrors
    url: https://unpkg.slqwq.cn
  - name: Comments API
    url: https://comments.api.slqwq.cn
  - name: Main Blog (Test for HEAD)
    method: HEAD
    url: https://blog.slqwq.cn
  - name: HomePage (Test for HEAD)
    method: HEAD
    url: https://slqwq.cn
  - name: Other CDN (Test for HEAD)
    method: HEAD
    url: https://moecdn.slqwq.cn
  - name: Static Files CDN (Test for HEAD)
    method: HEAD
    url: https://static.slqwq.cn
  - name: Static Files CDN Two (Test for HEAD)
    method: HEAD
    url: https://static-2.slqwq.cn
  - name: Static Files CDN Three (Test for HEAD)
    method: HEAD
    url: https://static-3.slqwq.cn
  - name: Unpkg Mirrors (Test for HEAD)
    method: HEAD
    url: https://unpkg.slqwq.cn
  - name: Comments API (Test for HEAD)
    method: HEAD
    url: https://comments.api.slqwq.cn

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: webstatus.slqwq.cn
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://moecdn.slqwq.cn/pic/logo.png
  name: Upptime
  introTitle: "这是** Hajeekn **的网站及服务状态检测"
  introMessage: 这是基于 upptime 制作的状态检测
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/hajeekn-co/testweb/
